#!/usr/bin/env bash
set -eu -o pipefail

bake_require bakescripts.sh

bake_log_level debug

BAKE_OPT_LOG_DEBUG_COLOR="$BAKE_COLOR_DGRAY"
BAKE_OPT_LOG_INFO_COLOR="$BAKE_COLOR_NORMAL"
BAKE_OPT_LOG_WARN_COLOR="$BAKE_COLOR_YELLOW"
BAKE_OPT_LOG_ERROR_COLOR="$BAKE_COLOR_LRED"
BAKE_OPT_LOG_FATAL_COLOR="$BAKE_COLOR_RED"

@bake_task "simple task"
function task.1 () {
  bake_log_debug "you ran a task!"
  bake_log_info "you ran a task!"
  bake_log_warn "you ran a task!"
  bake_log_error "you ran a task!"
  bake_log_fatal "you ran a task!"
}

@bake_task "pass me some args"
function task.2 {
  echo "You passed: $*"
}

@bake_task "move the bakefile to test when no file exists"
remove.bakefile () {
  echo "To restore Bakefile run:"
  echo "mv Bakefile{.bak,}"
  mv Bakefile{,.bak}
}

@bake_task my.func!
function my.func! () {
  bake_echo_green "foo"
}

function _bake_complete_task.2 () {
  docker ps --filter name=build --format "{{.Names}}"
}

function _bake_complete_task.1 () {
  get_completions docker "$@"
}

@bake_task
function this.is.a.really.long.task.name () {
  bake_echo_green "foo"
}

